import { Head, Link } from '@inertiajs/react';
import { index as postsIndex } from '@/routes/posts';

export default function Welcome() {
    return <><Head title="Readly — a place for useful ideas"/><div className="min-h-screen bg-[#f4f1ea] text-[#171714] selection:bg-[#d9ff52] selection:text-black">
        <header className="mx-auto flex max-w-7xl items-center justify-between px-6 py-7 sm:px-10"><Link href={postsIndex()} className="text-2xl font-black tracking-[-.08em]">READLY<span className="text-[#ff5a36]">/</span></Link><Link href={postsIndex()} className="rounded-full border-2 border-[#171714] px-5 py-2.5 text-xs font-black uppercase tracking-wider transition hover:bg-[#171714] hover:text-white">Enter the blog</Link></header>
        <main className="mx-auto max-w-7xl px-6 pb-20 pt-20 sm:px-10 lg:pt-28"><div className="grid gap-14 lg:grid-cols-[1fr_360px]"><div><p className="text-xs font-black uppercase tracking-[.28em] text-[#ff5a36]">Independent publishing platform</p><h1 className="mt-6 max-w-5xl text-[4.3rem] font-black leading-[.86] tracking-[-.075em] sm:text-7xl lg:text-[7.4rem]">Things<br/><span className="relative inline-block">worth <i className="absolute -bottom-1 left-0 h-2 w-full -rotate-1 bg-[#d9ff52]"/></span><br/>knowing.</h1><p className="mt-10 max-w-xl text-lg font-medium leading-8 text-black/55">Articles about technology, development, design, career, tools, ideas and the messy bits between them. No artificial categories. No filler.</p><Link href={postsIndex()} className="mt-9 inline-flex rounded-full bg-[#171714] px-7 py-4 text-sm font-black text-white transition hover:-translate-y-1">Browse latest posts ↗</Link></div><aside className="self-end"><div className="rotate-2 rounded-[2rem] bg-[#6d5dfc] p-7 text-white shadow-[12px_14px_0_#171714]"><p className="text-xs font-black uppercase tracking-widest text-white/60">What you'll find</p><div className="mt-10 space-y-6">{['Build better software.','Understand the tools.','Question the obvious.','Keep learning.'].map((x,i)=><div key={x} className="flex gap-4 border-t border-white/15 pt-4"><span className="font-mono text-xs text-white/50">0{i+1}</span><p className="font-bold">{x}</p></div>)}</div></div></aside></div><div className="mt-24 border-y-2 border-[#171714] py-5"><div className="flex flex-wrap items-center justify-between gap-4 text-xs font-black uppercase tracking-wider"><span>Read. Learn. Build. Repeat.</span><span>Latest ideas →</span><span>For curious humans.</span></div></div></main><footer className="mx-auto max-w-7xl px-6 py-10 text-xs font-bold text-black/35 sm:px-10">READLY / A blog, not a template.</footer>
    </div></>;
}
